services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENV=development
    volumes:
      - .:/app
      - backend_tmp:/app/tmp
    command: sh -c "go mod download && golangci-lint run ./... && air -c .air.toml"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run lint && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

volumes:
  backend_tmp:
