FROM golang:1.22

WORKDIR /app

# Install air
RUN go install github.com/air-verse/air@latest

# Install git
# RUN apt-get update && apt-get install -y git


COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]