info:
  contact: {}
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Get health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health
      tags:
      - health
swagger: "2.0"
